project_id = "sdmyvzolennegaropcfw"

[functions.vps-api]
verify_jwt = false

[functions.namesilo-api]
verify_jwt = false

[functions.process-order]
verify_jwt = false

[functions.check-dns]
verify_jwt = false

[functions.paystack]
verify_jwt = false

[functions.auto-suspend]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.check-expiring]
verify_jwt = false

[functions.coolify-api]
verify_jwt = false

[functions.admin-actions]
verify_jwt = false

[functions.health-check]
verify_jwt = false
